version: '3.4'

services:
  hellopostgres:
    image: ${DOCKER_REGISTRY-}hellopostgres
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    ports:
      - "8080:80"

  postgresdb:
    image: stellirin/postgres-windows
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: "M1llions2019"
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: nat
